---
- name: "Configure Lustre package repository"
  when: lustre_manage_repo | bool
  block:

    - name: Check Lustre repo URL is valid
      uri:
        url: "{{ lustre_repo_baseurl }}/{{ lustre_install_type }}"
        method: HEAD
      register: repo_uri_test
      failed_when: repo_uri_test.status != 200

    - name: "Install Lustre packages yum repo"
      yum_repository:
        name: "{{ lustre_repo_name }}"
        description: "{{ lustre_repo_description }}"
        baseurl: "{{ lustre_repo_baseurl }}/{{ lustre_install_type }}"
        gpgcheck: "{{ lustre_repo_gpgcheck | default('no') }}"
        gpgkey: "{{ lustre_repo_gpgkey | default(omit) }}"
        enabled: "{{ lustre_repo_enabled | default('no') }}"
      register: _lustre_repo

    - name: "Install lustre yum repo gpgkey"
      rpm_key:
        state: present
        key: "{{ lustre_repo_gpgkey }}"
        fingerprint: "{{ lustre_repo_gpgkey_fingerprint | default(omit) }}"
      when: lustre_repo_gpgkey is defined

    - name: "Clean yum cache if repository updated (1)"
      command: yum clean all
      args:
        warn: false
      when: _lustre_repo.changed

    - name: "Clean yum cache if repository updated (2)"
      command: rm -rf /var/cache/yum
      args:
        warn: false
      when: _lustre_repo.changed

